name: Hypem to Squarespace Sync

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run integration script
        env:
          HYPEM_USERNAME: ${{ secrets.HYPEM_USERNAME }}
          SQUARESPACE_API_KEY: ${{ secrets.SQUARESPACE_API_KEY }}
          SQUARESPACE_DOMAIN: ${{ secrets.SQUARESPACE_DOMAIN }}
          LAST_PROCESSED_ID: ${{ secrets.LAST_PROCESSED_ID }}
        run: python hypem_squarespace_integration.py
        
      - name: Update last processed ID
        if: ${{ env.NEW_LAST_PROCESSED_ID != '' }}
        run: |
          echo "Updating last processed ID to $NEW_LAST_PROCESSED_ID"
          echo "$NEW_LAST_PROCESSED_ID" > .last_processed_id
